[server]
port = 5000
cert_file = "big-bubba.pem"
cert_key = "big-bubba-key.pem"
log_level = "Debug"

[[service]]
id = 4
name = "DownService"
address = "8.8.8.8"
protocol_str= "TCP"  # This would map to the TCPProtocol struct, though you could expand the struct to add more fields.
start = "2025-03-15T10:00:00Z"
timer = 30

[[service]]
id = 5
name = "TestService"
address = "8.8.8.8"
protocol_str= "Test"  # This would map to the TCPProtocol struct, though you could expand the struct to add more fields.
timer = 5

[[service]]
id = 0
name = "Gitea"
address = "gitea.gplubeck.com:3000"
link = "https://gitea.gplubeck.com"
protocol_str= "TCP"  # This would map to the TCPProtocol struct, though you could expand the struct to add more fields.
icon = "gitea_logo.svg"
timer = 30
MaxHistory = 50

[[service]]
id = 1
name = "NotesPage"
address = "notes.gplubeck.com:443"
link = "https://notes.gplubeck.com"
protocol_str= "TCP"  # This would map to the TCPProtocol struct, though you could expand the struct to add more fields.
timer = 30

