[server]
port = 5000
cert_file = "big-bubba.pem"
cert_key = "big-bubba-key.pem"
log_level = "Debug"

[[service]]
id = 4
service_name = "DownService"
address = "8.8.8.8"
protocol_str= "TCP"
start = "2025-03-15T10:00:00Z"
timer = 30

[[service]]
id = 5
service_name = "Test Service"
address = "8.8.8.8"
protocol_str= "Test"
timer = 5
MaxHistory = 1000

[[service]]
id = 0
service_name = "Gitea"
address = "gitea.gplubeck.com:3000"
link = "https://gitea.gplubeck.com"
protocol_str= "TCP"
icon = "gitea_logo.svg"
timer = 30
MaxHistory = 500

[[service]]
id = 1
service_name = "Notes Page"
address = "notes.gplubeck.com:443"
link = "https://notes.gplubeck.com"
protocol_str= "TCP"
timer = 30

[[service]]
id = 2
service_name = "Jellyfin"
address = "tv.gplubeck.com:443"
link = "https://tv.gplubeck.com"
protocol_str= "UDP"
timer =  120 # every other minute
MaxHistory = 720 # one day

[[service]]
id = 3
service_name = "Home Page"
address = "gplubeck.com:443"
link = "https://gplubeck.com"
protocol_str= "TCP"
timer =  600 # every ten minutes
MaxHistory = 144 # one day

