[server]
port = 5000
cert_file = "big-bubba.pem" # optional server cert for TLS.  Without, will use plaintext.
cert_key = "big-bubba-key.pem" # optional server key for TLS
log_level = "warn"
theme = "material_dark.css" #customizable theme.  To Make your own, create a new .css in assets/css/ using the same css variables
title = "Real Time Service Status"
subtitle = "Stay up to date with service health."
storage_type = "memory" #currently on memory storage available


[[service]]
id = 5 # change to auto create ids
service_name = "Test Service" # Name to display in service card
address = "8.8.8.8:443"  # Addess to connect to.  Must have port
icon = "https://picsum.photos/200" # optional icon to display with service name, local or external img src
protocol_str= "Test" # TCP, UDP, or Test.  Test will return ~50% successful
timer = 5 # How often to probe in seconds
MaxHistory = 40 # How many health checks to keep
link = "https://google.com" # optional.  If used, will change service card header into a clickable item and redirect

[[service]]
id = 0
service_name = "Gitea"
address = "gitea.gplubeck.com:3000"
link = "https://gitea.gplubeck.com"
protocol_str= "TCP"
icon = "static/assets/gitea_logo.svg" #example of local icon
timer = 60
MaxHistory = 40

[[service]]
id = 3
service_name = "Home Page"
address = "gplubeck.com:443"
link = "https://gplubeck.com"
protocol_str= "TCP"
timer =  600 # every ten minutes
MaxHistory = 144 # one day

[[service]]
id = 6
service_name = "RSS Feed"
address = "rss.gplubeck.com:443"
link = "https://rss.gplubeck.com"
protocol_str= "TCP"
timer =  3600 # every hour 
MaxHistory = 40

[[service]]
id = 2
service_name = "Jellyfin"
address = "tv.gplubeck.com:443"
link = "https://tv.gplubeck.com"
protocol_str= "UDP"
timer =  120 # every other minute
MaxHistory = 40

[[service]]
id = 4 
service_name = "DownService" 
address = "8.8.8.8"
protocol_str= "TCP"
start = "2025-03-15T10:00:00Z"
timer = 30
MaxHistory = 40

[[service]]
id = 1
service_name = "Notes Page"
address = "notes.gplubeck.com:443"
link = "https://notes.gplubeck.com"
protocol_str= "TCP"
timer = 30
MaxHistory = 40
